---
title: "Data Wrangling Midterm"
output: 
  pdf_document: 
    keep_tex: yes
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




``` {r explore}
#install.packages("SASxport")
library(SASxport)
library(dplyr)
library(tidyr)
#SQL SAVE#
m1 <- read.xport("C:/Users/Alex/Desktop/desktop/Data Wrangling/Midterm/DIQ_I.XPT")


mydata <- read.xport("C:/Users/Alex/Desktop/desktop/Data Wrangling/Midterm/DIQ_I.XPT")

find_na <- function(x) {
  sum(is.na(x))
}

na_col <- apply(mydata, 2, find_na)
na_row <- apply(mydata, 1, find_na)
na_col_per <- na_col/9575
na_row_per <- na_row/54

sum(na_col_per>0.5) #47 columns have more than 50% of the data missing. 
sum(na_row_per>0.5) # all rows have more than 50% data missing


sum(na_col_per>0.9) # most(45) columns are missing more than 90% of data
sum(na_row_per>0.9) # Maybe get rid of all of these columns with 90% of data missing, which is 2534 rows.

library(plyr)

# find data types of each class
table(sapply(mydata, class))

#DIQ280 is NUMERICAL COLUMN

md2 <- mydata[(na_col_per<0.9)]
na_row2 <- apply(md2, 1, find_na)

na_row_per2 <- na_row2/7
sum(na_row_per2>0.5) #3389 have 4/7 NA per row. Do I keep these or get rid of them?

plot(density(na_row_per))

```




``` {r changena}
#sum(is.na(mydata$DID060))

# ont_col <- c("DID040","DID250","DIQ280", "DIQ300S","DIQ300D", "DID310S","DID310D","DID320","DID330", "DID341", "DID060", "DID350", "DID260")
# cc <- c("DID040","DID250")
# m1[,ont_col]

#subset(m1, select=(ont_col))


# Can't use 7, 77, 9, 99 Because it conflicts with continuous data
#mydata[mydata==7]<-NA
#mydata[mydata==77]<-NA
mydata[mydata==777]<-NA
mydata[mydata==7777]<-NA
#mydata[mydata==9]<-NA
#mydata[mydata==99]<-NA
mydata[mydata==999]<-NA
mydata[mydata==9999]<-NA

#install.packages("caret")
#library(caret)
```


``` {r c1}
sum(is.na(mydata$SEQN))
```


``` {r cat}
cat_col <- c("DIQ010","DIQ160","DIQ170","DIQ172","DIQ180","DIQ050","DIQ070","DIQ240","DIQ080", "DIQ275")
cat_col

colnames(mydata[cat_col])

#mydata[mydata==7]<-NA
#mydata[mydata==77]<-NA

#mydata[mydata==9]<-NA
#mydata[mydata==99]<-NA
m1["DIQ010"][m1["DIQ010"] == 7]

for (i in cat_col) {
  
  print(i)
  print(paste("Unique elements in",i))
  print(table(mydata[i]))
  print(paste("number of NA in", i,"is", sum(is.na(mydata[i]))))
  
  yes = paste(i,"yes",sep="_")
  no = paste(i,"no",sep="_")
  
  
  mydata[i][is.na(mydata[i])] <- 0
  mydata[i][mydata[i] == 7] <- 0
  mydata[i][mydata[i] == 77] <- 0
  mydata[i][mydata[i] == 9] <- 0
  mydata[i][mydata[i] == 99] <- 0
  n <- c()
  for (z in mydata[i][[1]]) {
    if (z == 1) {
      n <- append(n,1)
    } else {
      n <- append(n,0)
    }
  }
  m <- c()
  for (z in mydata[i][[1]]) {
    if (z == 2) {
      m <- append(m,1)
    } else {
      m <- append(m,0)
    }
  }
  
  mydata[,yes] <- as.factor(n)
  mydata[,no] <- as.factor(m)
  
}


mydata <- select(mydata, -c(cat_col))

head(mydata)

```



``` {r 175}
DIQ_one_col <- c("DIQ175A","DIQ175B","DIQ175C","DIQ175D","DIQ175E","DIQ175F","DIQ175G","DIQ175H","DIQ175I","DIQ175J","DIQ175K","DIQ175L","DIQ175M","DIQ175N","DIQ175O","DIQ175P","DIQ175Q","DIQ175R","DIQ175S","DIQ175T","DIQ175U","DIQ175V","DIQ175W","DIQ175X")

m2 <- mydata

for (i in DIQ_one_col) {
  print(i)
  print(paste("Unique elements in",i))
  print(table(mydata[i]))
  print(paste("number of NA in", i, sum(is.na(mydata[i]))))
        
  mydata[i][is.na(mydata[i])] <- 0
  mydata[i][mydata[i] == 7] <- 0
  mydata[i][mydata[i] == 77] <- 0
  mydata[i][mydata[i] == 9] <- 0
  mydata[i][mydata[i] == 99] <- 0
  n <- c()
  for (z in mydata[i][[1]]) {
    if (z == 0) {
      n <- append(n,0)
    } else {
      n <- append(n,1)
    }
  }
  mydata[,i] <- as.factor(n)
}
table(mydata$DIQ175A)


head(mydata)
```



``` {r cont2}
table(mydata$DID060)
class(mydata$DID060)
unique(mydata$DID060)
sum(is.na(mydata$DID060))
sum(is.na(m1$DID060))

mydata <- mydata %>% 
  mutate(DID060_format = ifelse(DID060==666, 6, 
                                ifelse(DIQ060U==1,DID060*12,
                                              ifelse(DIQ060U==2, DID060,DID060))))
table(mydata$DID060_format)
sum(is.na(mydata$DID060))

mydata <- select(mydata, -c(DID060,DIQ060U))

#DID260
table(mydata$DID260)
class(mydata$DID260)
unique(mydata$DID260)
sum(is.na(mydata$DID260))

mydata <- mydata %>% 
  mutate(DID260_format = ifelse(DID260==0,DID260,
                                ifelse(DIQ260U==1, DID260*365, 
                                ifelse(DIQ260U==2,DID260*52,
                                              ifelse(DIQ260U==3, DID260*12,
                                                     ifelse(DIQ260U==4, DID260, DID260))))))
table(mydata$DID260_format)

mydata <- select(mydata, -c(DID260,DIQ260U))

#DID350
table(mydata$DID350)
table(mydata$DID350_format)
class(mydata$DID350)
unique(mydata$DID350)
sum(is.na(mydata$DID350))

mydata <- mydata %>% 
  mutate(DID350_format = ifelse(DID350==0, DID350,
                                ifelse(DIQ350U==1, DID350*365, 
                                ifelse(DIQ350U==2,DID350*52,
                                              ifelse(DID350==3, DID350*12,
                                                     ifelse(DIQ350U==4, DID350, DID350))))))
table(mydata$DID350_format)

table(m1$DID350)
mydata <- select(mydata, -c(DID350,DIQ350U))

head(mydata)
```

``` {r cat2}
table(mydata$DIQ230)
sum(is.na(mydata$DIQ230))
class(mydata$DIQ230)

unique(mydata$DIQ230)


mydata <- mydata %>% 
  mutate(DIQ230_1 = ifelse(DIQ230==1, 1, 0),
         DIQ230_2 = ifelse(DIQ230==2, 1, 0),
         DIQ230_3 = ifelse(DIQ230==3, 1, 0),
         DIQ230_4 = ifelse(DIQ230==4, 1, 0),
         DIQ230_Never = ifelse(DIQ230==5, 1, 0))

table(mydata$DIQ230_1)
table(mydata$DIQ230_2)
table(mydata$DIQ230_3)
table(mydata$DIQ230_4)
table(mydata$DIQ230_Never)


mydata$DIQ230_1 <- as.factor(mydata$DIQ230_1)
mydata$DIQ230_2 <- as.factor(mydata$DIQ230_2)
mydata$DIQ230_3 <- as.factor(mydata$DIQ230_3)
mydata$DIQ230_4 <- as.factor(mydata$DIQ230_4)
mydata$DIQ230_Never <- as.factor(mydata$DIQ230_Never)

mydata["DIQ230_1"][is.na(mydata["DIQ230_1"])] <- 0
mydata["DIQ230_2"][is.na(mydata["DIQ230_2"])] <- 0
mydata["DIQ230_3"][is.na(mydata["DIQ230_3"])] <- 0
mydata["DIQ230_4"][is.na(mydata["DIQ230_4"])] <- 0
mydata["DIQ230_Never"][is.na(mydata["DIQ230_Never"])] <- 0

mydata <- select(mydata, -c(DIQ230))

#DIQ291 # can encode 6 as NA Because 6 is Provider did not specify goal.
table(mydata$DIQ291)
sum(is.na(mydata$DIQ291))
class(mydata$DIQ291)

unique(mydata$DIQ291)


mydata <- mydata %>% 
  mutate(DIQ291_1 = ifelse(DIQ291==1, 1, 0),
         DIQ291_2 = ifelse(DIQ291==2, 1, 0),
         DIQ291_3 = ifelse(DIQ291==3, 1, 0),
         DIQ291_4 = ifelse(DIQ291==4, 1, 0),
         DIQ291_5 = ifelse(DIQ291==5, 1, 0),
         DIQ291_6 = ifelse(DIQ291==6, 1, 0))

table(mydata$DIQ291_1)
table(mydata$DIQ291_2)
table(mydata$DIQ291_3)
table(mydata$DIQ291_4)
table(mydata$DIQ291_5)
table(mydata$DIQ291_6)

mydata$DIQ291_1 <- as.factor(mydata$DIQ291_1)
mydata$DIQ291_2 <- as.factor(mydata$DIQ291_2)
mydata$DIQ291_3 <- as.factor(mydata$DIQ291_3)
mydata$DIQ291_4 <- as.factor(mydata$DIQ291_4)
mydata$DIQ291_5 <- as.factor(mydata$DIQ291_5)
mydata$DIQ291_6 <- as.factor(mydata$DIQ291_6)

mydata["DIQ291_1"][is.na(mydata["DIQ291_1"])] <- 0
mydata["DIQ291_2"][is.na(mydata["DIQ291_2"])] <- 0
mydata["DIQ291_3"][is.na(mydata["DIQ291_3"])] <- 0
mydata["DIQ291_4"][is.na(mydata["DIQ291_4"])] <- 0
mydata["DIQ291_5"][is.na(mydata["DIQ291_5"])] <- 0
mydata["DIQ291_6"][is.na(mydata["DIQ291_6"])] <- 0


mydata <- select(mydata, -c(DIQ291))


#DIQ360 
table(mydata$DIQ360)
sum(is.na(mydata$DIQ360))
class(mydata$DIQ360)

unique(mydata$DIQ360)


mydata <- mydata %>% 
  mutate(DIQ360_1 = ifelse(DIQ360==1, 1, 0),
         DIQ360_2 = ifelse(DIQ360==2, 1, 0),
         DIQ360_3 = ifelse(DIQ360==3, 1, 0),
         DIQ360_4 = ifelse(DIQ360==4, 1, 0),
         DIQ360_5 = ifelse(DIQ360==5, 1, 0))

table(mydata$DIQ360_1)
table(mydata$DIQ360_2)
table(mydata$DIQ360_3)
table(mydata$DIQ360_4)
table(mydata$DIQ360_5)

mydata$DIQ360_1 <- as.factor(mydata$DIQ360_1)
mydata$DIQ360_2 <- as.factor(mydata$DIQ360_2)
mydata$DIQ360_3 <- as.factor(mydata$DIQ360_3)
mydata$DIQ360_4 <- as.factor(mydata$DIQ360_4)
mydata$DIQ360_5 <- as.factor(mydata$DIQ360_5)



mydata <- select(mydata, -c(DIQ360))



mydata["DIQ360_1"][is.na(mydata["DIQ360_1"])] <- 0
mydata["DIQ360_2"][is.na(mydata["DIQ360_2"])] <- 0
mydata["DIQ360_3"][is.na(mydata["DIQ360_3"])] <- 0
mydata["DIQ360_4"][is.na(mydata["DIQ360_4"])] <- 0
mydata["DIQ360_5"][is.na(mydata["DIQ360_5"])] <- 0

sum(is.na(mydata$DIQ360_1))

head(mydata)
```



``` {r }
# change 666 to 0.5
table(mydata$DID040)
sum(is.na(mydata$DID040))
mydata <- mydata %>%
  mutate(DID040 =ifelse(DID040==666, 0.5,DID040))


table(mydata$DID250)
sum(is.na(mydata$DID260))

table(mydata$DIQ280)
sum(is.na(mydata$DIQ280))

table(mydata$DIQ300S)
sum(is.na(mydata$DIQ300S))

table(mydata$DIQ300D)
sum(is.na(mydata$DIQ300D))

table(mydata$DID310S)
sum(is.na(mydata$DID310S))
mydata$DID310S[mydata$DID310S==6666]<-NA

table(mydata$DID310D)
sum(is.na(mydata$DID310D))
mydata$DID310D[mydata$DID310D==6666]<-NA

table(mydata$DID320)
sum(is.na(mydata$DID320))
mydata$DID320[mydata$DID320==5555]<-NA
mydata$DID320[mydata$DID320==6666]<-NA

table(mydata$DID330)
sum(is.na(mydata$DID330))
mydata$DID330[mydata$DID330==6666]<-NA

table(mydata$DID341)
sum(is.na(mydata$DID341))


# Need to code the NA's in reformatted continuous columns from above
table(mydata$DID060_format)
table(mydata$DID350_format)
table(mydata$DID260_format)


# Reformat Continuous columns to add -1 instead of NA


cont_col <- c("DID040","DID250","DIQ280", "DIQ300S","DIQ300D", "DID310S","DID310D","DID320","DID330", "DID341", "DID060_format", "DID350_format", "DID260_format")

for (i in cont_col) {
  mydata[i][is.na(mydata[i])] <- -1
  
}


head(mydata)

#sum(is.na(mydata$DID060))

#m1["DID060"][is.na(m1["DID060"])] <- -1
#table(m1$DID060)
```






``` {r checkitem}

"DIQ065" %in% names(mydata) # Doesn't exist
"DIQ229" %in% names(mydata) # Doesn't exist
"DIQ295" %in% names(mydata) # Doesn't exist
"DIQ159" %in% names(mydata) # Doesn't exist

```



``` {r data dictionary}
library(sqldf)

#1
sqldf("SELECT COUNT(DIQ010_yes)
FROM mydata
WHERE DIQ010_yes = 1")

#2
sqldf("SELECT COUNT(DIQ010_no)
FROM mydata
WHERE DIQ010_no = 1")

#3
sqldf("SELECT COUNT(DID040)
FROM mydata
WHERE DID040 != -1")

#4
sqldf("SELECT COUNT(DIQ160_yes)
FROM mydata
WHERE DIQ160_yes = 1")

#5
sqldf("SELECT COUNT(DIQ160_no)
FROM mydata
WHERE DIQ160_no = 1")

#6
sqldf("SELECT COUNT(DIQ170_yes)
FROM mydata
WHERE DIQ170_yes = 1")

#7
sqldf("SELECT COUNT(DIQ170_no)
FROM mydata
WHERE DIQ170_no = 1")

#8
sqldf("SELECT COUNT(DIQ172_yes)
FROM mydata
WHERE DIQ172_yes = 1")

#9
sqldf("SELECT COUNT(DIQ172_no)
FROM mydata
WHERE DIQ172_no = 1")

#10
sqldf("SELECT COUNT(DIQ175A)
FROM mydata
WHERE DIQ175A = 1")

#11
sqldf("SELECT COUNT(DIQ175B)
FROM mydata
WHERE DIQ175B = 1")

#12
sqldf("SELECT COUNT(DIQ175C)
FROM mydata
WHERE DIQ175C = 1")

#13
sqldf("SELECT COUNT(DIQ175D)
FROM mydata
WHERE DIQ175D = 1")

#14
sqldf("SELECT COUNT(DIQ175E)
FROM mydata
WHERE DIQ175E = 1")

#15
sqldf("SELECT COUNT(DIQ175F)
FROM mydata
WHERE DIQ175F = 1")

#16
sqldf("SELECT COUNT(DIQ175G)
FROM mydata
WHERE DIQ175G = 1")

#17
sqldf("SELECT COUNT(DIQ175H)
FROM mydata
WHERE DIQ175H = 1")

#18
sqldf("SELECT COUNT(DIQ175I)
FROM mydata
WHERE DIQ175I = 1")

#19
sqldf("SELECT COUNT(DIQ175J)
FROM mydata
WHERE DIQ175J = 1")

#20
sqldf("SELECT COUNT(DIQ175K)
FROM mydata
WHERE DIQ175K = 1")

#21
sqldf("SELECT COUNT(DIQ175L)
FROM mydata
WHERE DIQ175L = 1")

#22
sqldf("SELECT COUNT(DIQ175M)
FROM mydata
WHERE DIQ175M = 1")

#23
sqldf("SELECT COUNT(DIQ175N)
FROM mydata
WHERE DIQ175N = 1")

#24
sqldf("SELECT COUNT(DIQ175O)
FROM mydata
WHERE DIQ175O = 1")

#25
sqldf("SELECT COUNT(DIQ175P)
FROM mydata
WHERE DIQ175P = 1")

#26
sqldf("SELECT COUNT(DIQ175Q)
FROM mydata
WHERE DIQ175Q = 1")

#27
sqldf("SELECT COUNT(DIQ175R)
FROM mydata
WHERE DIQ175R = 1")

#28
sqldf("SELECT COUNT(DIQ175S)
FROM mydata
WHERE DIQ175S = 1")

#29
sqldf("SELECT COUNT(DIQ175T)
FROM mydata
WHERE DIQ175T = 1")

#30
sqldf("SELECT COUNT(DIQ175U)
FROM mydata
WHERE DIQ175U = 1")

#31
sqldf("SELECT COUNT(DIQ175V)
FROM mydata
WHERE DIQ175V = 1")

#32
sqldf("SELECT COUNT(DIQ175W)
FROM mydata
WHERE DIQ175W = 1")

#33
sqldf("SELECT COUNT(DIQ175X)
FROM mydata
WHERE DIQ175X = 1")

#34
sqldf("SELECT COUNT(DIQ180_yes)
FROM mydata
WHERE DIQ180_yes = 1")

#35
sqldf("SELECT COUNT(DIQ180_no)
FROM mydata
WHERE DIQ180_no = 1")

#36
sqldf("SELECT COUNT(DIQ050_yes)
FROM mydata
WHERE DIQ050_yes = 1")

#37
sqldf("SELECT COUNT(DIQ050_no)
FROM mydata
WHERE DIQ050_no = 1")

#38
sqldf("SELECT COUNT(DID060_format)
FROM mydata
WHERE DID060_format != -1")

#39
sqldf("SELECT COUNT(DIQ070_yes)
FROM mydata
WHERE DIQ070_yes = 1")

#40
sqldf("SELECT COUNT(DIQ070_no)
FROM mydata
WHERE DIQ070_no = 1")

#41
sqldf("SELECT COUNT(DIQ230_1)
FROM mydata
WHERE DIQ230_1 = 1")

#42
sqldf("SELECT COUNT(DIQ230_2)
FROM mydata
WHERE DIQ230_2 = 1")

#43
sqldf("SELECT COUNT(DIQ230_3)
FROM mydata
WHERE DIQ230_3 = 1")

#44
sqldf("SELECT COUNT(DIQ230_4)
FROM mydata
WHERE DIQ230_4 = 1")

#45
sqldf("SELECT COUNT(DIQ230_Never)
FROM mydata
WHERE DIQ230_Never = 1")

#46
sqldf("SELECT COUNT(DIQ240_yes)
FROM mydata
WHERE DIQ240_yes = 1")

#47
sqldf("SELECT COUNT(DIQ240_no)
FROM mydata
WHERE DIQ240_no = 1")

#48
sqldf("SELECT COUNT(DID250)
FROM mydata
WHERE DID250 = -1")

#49
sqldf("SELECT COUNT(DID260_format)
FROM mydata
WHERE DID260_format != -1")

#50
sqldf("SELECT COUNT(DIQ275_yes)
FROM mydata
WHERE DIQ275_yes = 1")

#51
sqldf("SELECT COUNT(DIQ275_no)
FROM mydata
WHERE DIQ275_no = 1")

#52
sqldf("SELECT COUNT(DIQ280)
FROM mydata
WHERE DIQ280 = -1")

#53
sqldf("SELECT COUNT(DIQ291_1)
FROM mydata
WHERE DIQ291_1 = 1")

#54
sqldf("SELECT COUNT(DIQ291_2)
FROM mydata
WHERE DIQ291_2 = 1")

#55
sqldf("SELECT COUNT(DIQ291_3)
FROM mydata
WHERE DIQ291_3 = 1")

#56
sqldf("SELECT COUNT(DIQ291_4)
FROM mydata
WHERE DIQ291_4 = 1")

#57
sqldf("SELECT COUNT(DIQ291_5)
FROM mydata
WHERE DIQ291_5 = 1")

#58
sqldf("SELECT COUNT(DIQ291_6)
FROM mydata
WHERE DIQ291_6 = 1")

#59
sqldf("SELECT COUNT(DIQ300S)
FROM mydata
WHERE DIQ300S != -1")

#60
sqldf("SELECT COUNT(DIQ300D)
FROM mydata
WHERE DIQ300D != -1")

#61
sqldf("SELECT COUNT(DID310S)
FROM mydata
WHERE DID310S != -1")

#62
sqldf("SELECT COUNT(DID310D)
FROM mydata
WHERE DID310D != -1")


#64
sqldf("SELECT COUNT(DID320)
FROM mydata
WHERE DID320 != -1")

#65
sqldf("SELECT COUNT(DID330)
FROM mydata
WHERE DID330 != -1")

#66
sqldf("SELECT COUNT(DID341)
FROM mydata
WHERE DID341 != -1")

#67
sqldf("SELECT COUNT(DID350_format)
FROM mydata
WHERE DID350_format != -1")

#68
sqldf("SELECT COUNT(DIQ360_1)
FROM mydata
WHERE DIQ360_1 = 1")

#69
sqldf("SELECT COUNT(DIQ360_2)
FROM mydata
WHERE DIQ360_2 = 1")

#70
sqldf("SELECT COUNT(DIQ360_3)
FROM mydata
WHERE DIQ360_3 = 1")

#71
sqldf("SELECT COUNT(DIQ360_4)
FROM mydata
WHERE DIQ360_4 = 1")

#72
sqldf("SELECT COUNT(DIQ360_5)
FROM mydata
WHERE DIQ360_5 = 1")

#73
sqldf("SELECT COUNT(DIQ080_yes)
FROM mydata
WHERE DIQ080_yes = 1")

#74
sqldf("SELECT COUNT(DIQ080_no)
FROM mydata
WHERE DIQ080_no = 1")

```




``` {r head}
head(mydata)

```

















































